version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3.2.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=187LOL187
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
