version: '3.9'

services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=187LOL187
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: unless-stopped

  notizen-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - couchdb
    volumes:
      - ./app:/usr/src/app/app
    stdin_open: true
    tty: true

volumes:
  couchdb_data:
